namespace: quickstart-standalone
cluster_mode: standalone
mask:
  database_plan: true
  storage_plan: true
  ingress: true
  registry: true
  proxy: false
  custom_tls: false
database_plan:
  name: eph-db
  type: ephemeral
storage_plan:
  name: eph-st
  type: ephemeral
ingress:
  type: kubernetes-ingress
  enable_tls: false
  k8s_ingress:
    domain: quickstart-standalone.nl
    useCustomIngressClass: true
    customIngressClass: nginx
    customIngressClassAsAnnotation: true
    path: /
  service: null
registry:
  type: generic
  generic_registry:
    auth_pull_url: TODO
    auth_push_url: TODO
    registry_name: TODO
    enable_auth: true
    auth_user: TODO
    auth_password: TODO
    link_secret_to_service_account: false
